<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ramon de Araujo Soares">

<title>Roteiro para aula pratica - Métodos quantitativos aplicados à administração</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="trilha-completa_files/libs/clipboard/clipboard.min.js"></script>
<script src="trilha-completa_files/libs/quarto-html/quarto.js"></script>
<script src="trilha-completa_files/libs/quarto-html/popper.min.js"></script>
<script src="trilha-completa_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="trilha-completa_files/libs/quarto-html/anchor.min.js"></script>
<link href="trilha-completa_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="trilha-completa_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="trilha-completa_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="trilha-completa_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="trilha-completa_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Roteiro para aula pratica - Métodos quantitativos aplicados à administração</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ramon de Araujo Soares </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="caso-prático---utilização-da-regressão-linear-múltipla" class="level1">
<h1>Caso prático - utilização da regressão linear múltipla</h1>
<section id="roteiro" class="level2">
<h2 class="anchored" data-anchor-id="roteiro">Roteiro:</h2>
<ol type="1">
<li>Introdução</li>
<li>Github - ferramenta de armazenamento, versionamento e trabalho em equipe.</li>
<li>Uso de inteligência artificial generativa</li>
<li>Apresentação do caso e descrição dos passos para criação do modelo e análise.</li>
<li>Atividade prática</li>
</ol>
</section>
<section id="etapas-passo-a-passo" class="level2">
<h2 class="anchored" data-anchor-id="etapas-passo-a-passo">Etapas (passo-a-passo)</h2>
<ol type="1">
<li><p>Preparar e tratar os dados</p></li>
<li><p>Descrever os dados</p></li>
<li><p>Analisar correlação entre as variáveis</p></li>
<li><p>Verificar pressupostos da regressão</p></li>
<li><p>Calcular amostra</p></li>
<li><p>Expressar as hipóteses da regressão</p></li>
<li><p>Modelar e analisar regressão</p></li>
<li><p>Interpretar e relatar os resultados</p></li>
</ol>
</section>
<section id="caso" class="level2">
<h2 class="anchored" data-anchor-id="caso">Caso</h2>
<p>Você é um(a) analista de logística em uma empresa e está preocupado(a) com o aumento dos <strong>custos de frete</strong>, que têm impactado negativamente os resultados financeiros. Para entender melhor os fatores que influenciam esses custos, você decide usar a ferramenta de <strong>regressão múltipla</strong> e criar um modelo estatístico capaz de quantificar o impacto de variáveis operacionais como distância percorrida e peso da carga. Após uma exploração inicial dos dados que tinha à disposição, você conseguiu extrair dos sistemas de informação da empresa dois relatórios contendo dados relevantes, que serão utilizados para estruturar sua pesquisa e apoiar decisões estratégicas voltadas à redução de custos e aumento da eficiência logística.</p>
<p>Os arquivos extraídos do sistema foram:<br>
relatorio1.csv<br>
relatorio2.csv</p>
<p>As variáveis a serem utilizadas no estudo estão listadas a seguir.</p>
<p><strong>Variável dependente:</strong></p>
<p>Custo de transporte (custo_frete)</p>
<p><strong>Variáveis independentes:</strong></p>
<p>Distância (distancia_km)<br>
Peso da carga (peso_carga_kg)<br>
Consumo de combustível (consumo_combustivel_kml)<br>
Temperatura do ambiente (temperatura_ambiente)<br>
Horário do envio (hora_envio)</p>
<hr>
</section>
<section id="carregar-bibliotecas-que-serão-utilizadas" class="level2">
<h2 class="anchored" data-anchor-id="carregar-bibliotecas-que-serão-utilizadas">0. Carregar bibliotecas que serão utilizadas</h2>
<p>Verifique as bibliotecas necessárias já foram instaladas previamente. Comando library() ou na interface gráfica do RStudio - Packages</p>
<p>Se precisar instalar: Usar install.packages(c(““,”“,”“,”“)) ou, no painel do RStudio, pela aba ‘Packages’</p>
<p>Atenção para os possíveis conflitos que podem acontecer ao carregar mais de uma biblioteca! Isso pode demandar ajustes no uso de alguma função.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Carregando pacotes exigidos: carData</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(carData)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>corrplot 0.95 loaded</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Anexando pacote: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>O seguinte objeto é mascarado por 'package:car':

    recode</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Os seguintes objetos são mascarados por 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Os seguintes objetos são mascarados por 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Carregando pacotes exigidos: zoo</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Anexando pacote: 'zoo'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Os seguintes objetos são mascarados por 'package:base':

    as.Date, as.Date.numeric</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pwr)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="tratar-os-dados" class="level2">
<h2 class="anchored" data-anchor-id="tratar-os-dados">1. Tratar os dados</h2>
<section id="reunir-dados-dos-arquivos-em-um-dataframe" class="level4">
<h4 class="anchored" data-anchor-id="reunir-dados-dos-arquivos-em-um-dataframe">1.1 Reunir dados dos arquivos em um dataframe</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>relatorio1 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"relatorio1.csv"</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>relatorio2 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"relatorio2.csv"</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>dadoscombinados <span class="ot">&lt;-</span> <span class="fu">merge</span>(relatorio1, relatorio2, <span class="at">by =</span> <span class="st">"id"</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualizar cabeçalho para conferir se a extração foi correta:</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dadoscombinados)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  id custo_frete distancia_km peso_carga_kg consumo_combustivel_kml
1  1   33291.160     593.0832      5961.421                7.098845
2  2  -20341.346    1428.5357     16486.078                7.062083
3  3    9212.147    4993.3751     26251.902                      NA
4  4    8739.984     918.0548     22100.634               11.163008
5  5    3772.394     276.2270     24293.554               12.905279
6  6    3035.708     276.1921     19934.109                4.759300
  temperatura_ambiente hora_envio
1            -9.170376   22.58382
2            23.085934   14.95705
3            20.122472   17.79905
4           158.543269   19.32234
5             1.690642   20.28095
6            -8.814612    9.48128</code></pre>
</div>
</div>
</section>
<section id="campos-vazios" class="level4">
<h4 class="anchored" data-anchor-id="campos-vazios">1.2 Campos vazios</h4>
<ol type="1">
<li>Identificar quantas entradas têm campos vazios (campos com valor NA)</li>
<li>Retirar entradas com campos vazios</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#contar quantas entradas em 'dadoscombinados' tem campos vazios</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(dadoscombinados))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#criar novo conjunto de dados retirando campos vazios de 'dadoscombinados'</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>dados_trata_NA <span class="ot">&lt;-</span> tidyr<span class="sc">::</span><span class="fu">drop_na</span>(dadoscombinados)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co">#contar quantas entradas tem campos vazios no novo conjunto de dados criado (verificar se é 0!)</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(dados_trata_NA)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p><strong>1.3 Dados inconsistentes e dados extremos</strong></p>
<p>Sumário estatístico prévio para entender os dados e identificar inconsistências</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dados_trata_NA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       id          custo_frete      distancia_km     peso_carga_kg    
 Min.   :   1.0   Min.   :-20341   Min.   :  56.72   Min.   :  594.9  
 1st Qu.: 253.0   1st Qu.:  5237   1st Qu.: 385.06   1st Qu.: 7640.3  
 Median : 504.0   Median :  7065   Median : 771.01   Median :15812.3  
 Mean   : 502.1   Mean   :  7076   Mean   : 766.67   Mean   :15464.4  
 3rd Qu.: 751.0   3rd Qu.:  9004   3rd Qu.:1133.83   3rd Qu.:22928.5  
 Max.   :1000.0   Max.   : 33291   Max.   :2585.47   Max.   :29982.7  
 consumo_combustivel_kml temperatura_ambiente   hora_envio      
 Min.   : 3.017          Min.   : -9.998      Min.   : 0.02264  
 1st Qu.: 5.872          1st Qu.:  1.953      1st Qu.: 6.06810  
 Median : 8.823          Median : 14.309      Median :11.80804  
 Mean   : 8.917          Mean   : 14.709      Mean   :12.03910  
 3rd Qu.:12.106          3rd Qu.: 27.078      3rd Qu.:17.69835  
 Max.   :22.878          Max.   :158.543      Max.   :39.88109  </code></pre>
</div>
</div>
<p>Tratar valores negativos no custo_frete</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Contar os valores negativos na variável custo_frete</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>valores_negativos <span class="ot">&lt;-</span> <span class="fu">sum</span>(dados_trata_NA<span class="sc">$</span>custo_frete <span class="sc">&lt;</span> <span class="dv">0</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Número de valores negativos em custo_frete:"</span>, valores_negativos, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Número de valores negativos em custo_frete: 1 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Excluir os valores negativos do dataframe</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>dados_trata_NA_nega <span class="ot">&lt;-</span> dados_trata_NA[dados_trata_NA<span class="sc">$</span>custo_frete <span class="sc">&gt;=</span> <span class="dv">0</span>, ]</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Confirmar a exclusão</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Dimensão do dataframe após exclusão:"</span>, <span class="fu">dim</span>(dados_trata_NA_nega), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Dimensão do dataframe após exclusão: 988 7 </code></pre>
</div>
</div>
<p>Listar os outliers de cada variável.<br>
Obs1: Considerar outliers valores maiores que 3 desvios padrão.<br>
Obs2: Listar outliers antes e depois do tratamento para conferir se o tratamento foi feito</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Variáveis do dataframe</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>variaveis <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"custo_frete"</span>, <span class="st">"distancia_km"</span>, <span class="st">"peso_carga_kg"</span>, <span class="st">"consumo_combustivel_kml"</span>, <span class="st">"temperatura_ambiente"</span>, <span class="st">"hora_envio"</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Função para identificar outliers (3 desvios padrão)</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>identificar_outliers <span class="ot">&lt;-</span> <span class="cf">function</span>(data, variaveis) {</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  outliers_list <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Loop por cada variável especificada</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (coluna <span class="cf">in</span> variaveis) {</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>    media <span class="ot">&lt;-</span> <span class="fu">mean</span>(data[[coluna]], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>    desvio_padrao <span class="ot">&lt;-</span> <span class="fu">sd</span>(data[[coluna]], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Identificar os outliers</span></span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>    outliers <span class="ot">&lt;-</span> data[</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>      data[[coluna]] <span class="sc">&lt;</span> (media <span class="sc">-</span> <span class="dv">3</span> <span class="sc">*</span> desvio_padrao) <span class="sc">|</span></span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>      data[[coluna]] <span class="sc">&gt;</span> (media <span class="sc">+</span> <span class="dv">3</span> <span class="sc">*</span> desvio_padrao),</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>      coluna,</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>      drop <span class="ot">=</span> <span class="cn">FALSE</span></span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>    ]</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Armazenar os outliers</span></span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>    outliers_list[[coluna]] <span class="ot">&lt;-</span> outliers</span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(outliers_list)</span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Identificar os outliers antes do tratamento</span></span>
<span id="cb27-28"><a href="#cb27-28" aria-hidden="true" tabindex="-1"></a>outliers_antes <span class="ot">&lt;-</span> <span class="fu">identificar_outliers</span>(dados_trata_NA_nega, variaveis)</span>
<span id="cb27-29"><a href="#cb27-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-30"><a href="#cb27-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Remover os outliers do dataframe</span></span>
<span id="cb27-31"><a href="#cb27-31" aria-hidden="true" tabindex="-1"></a>remover_outliers <span class="ot">&lt;-</span> <span class="cf">function</span>(data, variaveis) {</span>
<span id="cb27-32"><a href="#cb27-32" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (coluna <span class="cf">in</span> variaveis) {</span>
<span id="cb27-33"><a href="#cb27-33" aria-hidden="true" tabindex="-1"></a>    media <span class="ot">&lt;-</span> <span class="fu">mean</span>(data[[coluna]], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb27-34"><a href="#cb27-34" aria-hidden="true" tabindex="-1"></a>    desvio_padrao <span class="ot">&lt;-</span> <span class="fu">sd</span>(data[[coluna]], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb27-35"><a href="#cb27-35" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb27-36"><a href="#cb27-36" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Filtrar os valores dentro de 3 desvios padrão</span></span>
<span id="cb27-37"><a href="#cb27-37" aria-hidden="true" tabindex="-1"></a>    data <span class="ot">&lt;-</span> data[</span>
<span id="cb27-38"><a href="#cb27-38" aria-hidden="true" tabindex="-1"></a>      data[[coluna]] <span class="sc">&gt;=</span> (media <span class="sc">-</span> <span class="dv">3</span> <span class="sc">*</span> desvio_padrao) <span class="sc">&amp;</span></span>
<span id="cb27-39"><a href="#cb27-39" aria-hidden="true" tabindex="-1"></a>      data[[coluna]] <span class="sc">&lt;=</span> (media <span class="sc">+</span> <span class="dv">3</span> <span class="sc">*</span> desvio_padrao),</span>
<span id="cb27-40"><a href="#cb27-40" aria-hidden="true" tabindex="-1"></a>      , drop <span class="ot">=</span> <span class="cn">FALSE</span></span>
<span id="cb27-41"><a href="#cb27-41" aria-hidden="true" tabindex="-1"></a>    ]</span>
<span id="cb27-42"><a href="#cb27-42" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb27-43"><a href="#cb27-43" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(data)</span>
<span id="cb27-44"><a href="#cb27-44" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb27-45"><a href="#cb27-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-46"><a href="#cb27-46" aria-hidden="true" tabindex="-1"></a><span class="co"># Aplicar o tratamento de outliers</span></span>
<span id="cb27-47"><a href="#cb27-47" aria-hidden="true" tabindex="-1"></a>dados_trata_final <span class="ot">&lt;-</span> <span class="fu">remover_outliers</span>(dados_trata_NA_nega, variaveis)</span>
<span id="cb27-48"><a href="#cb27-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-49"><a href="#cb27-49" aria-hidden="true" tabindex="-1"></a><span class="co"># Identificar os outliers depois do tratamento (deve ser vazio)</span></span>
<span id="cb27-50"><a href="#cb27-50" aria-hidden="true" tabindex="-1"></a>outliers_depois <span class="ot">&lt;-</span> <span class="fu">identificar_outliers</span>(dados_trata_final, variaveis)</span>
<span id="cb27-51"><a href="#cb27-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-52"><a href="#cb27-52" aria-hidden="true" tabindex="-1"></a><span class="co"># Exibir os outliers antes e depois do tratamento</span></span>
<span id="cb27-53"><a href="#cb27-53" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Outliers antes do tratamento:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Outliers antes do tratamento:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(outliers_antes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$custo_frete
  custo_frete
1    33291.16

$distancia_km
    distancia_km
9       2539.553
12      2554.746
23      2569.248
211     2585.470

$peso_carga_kg
[1] peso_carga_kg
&lt;0 linhas&gt; (ou row.names de comprimento 0)

$consumo_combustivel_kml
    consumo_combustivel_kml
376                22.87761

$temperatura_ambiente
    temperatura_ambiente
3              158.54327
219             75.02405

$hora_envio
    hora_envio
106   39.88109
953   39.63195</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Outliers depois do tratamento:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Outliers depois do tratamento:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(outliers_depois)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$custo_frete
[1] custo_frete
&lt;0 linhas&gt; (ou row.names de comprimento 0)

$distancia_km
[1] distancia_km
&lt;0 linhas&gt; (ou row.names de comprimento 0)

$peso_carga_kg
[1] peso_carga_kg
&lt;0 linhas&gt; (ou row.names de comprimento 0)

$consumo_combustivel_kml
[1] consumo_combustivel_kml
&lt;0 linhas&gt; (ou row.names de comprimento 0)

$temperatura_ambiente
[1] temperatura_ambiente
&lt;0 linhas&gt; (ou row.names de comprimento 0)

$hora_envio
[1] hora_envio
&lt;0 linhas&gt; (ou row.names de comprimento 0)</code></pre>
</div>
</div>
<p><strong>ATIVIDADE:<br>
Refazer o tratamento de dados</strong></p>
<p><strong>ATIVIDADE:<br>
Criar gráfico boxplot para visualizar os outliers de cada variável antes do tratamento<br>
</strong>obs: vetor dos dados a ser utilizado é ’dados_trata_NA_nega</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Função para criar boxplots no RStudio (dados antes do tratamento)</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>criar_boxplots_antes <span class="ot">&lt;-</span> <span class="cf">function</span>(data_antes, variaveis) {</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (coluna <span class="cf">in</span> variaveis) {</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Criar dataframe para a variável</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>    data_plot <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">Valor =</span> data_antes[[coluna]],</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">Variavel =</span> coluna</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Gerar o boxplot</span></span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>(</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>      <span class="fu">ggplot</span>(data_plot, <span class="fu">aes</span>(<span class="at">x =</span> Variavel, <span class="at">y =</span> Valor)) <span class="sc">+</span></span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>        <span class="fu">geom_boxplot</span>(<span class="at">outlier.color =</span> <span class="st">"red"</span>, <span class="at">outlier.size =</span> <span class="dv">2</span>, <span class="at">fill =</span> <span class="st">"skyblue"</span>) <span class="sc">+</span></span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>        <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste</span>(<span class="st">"Boxplot Antes do Tratamento -"</span>, coluna),</span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>             <span class="at">x =</span> <span class="st">"Variável"</span>,</span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>             <span class="at">y =</span> <span class="st">"Valores"</span>) <span class="sc">+</span></span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a>        <span class="fu">theme_minimal</span>()</span>
<span id="cb35-18"><a href="#cb35-18" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb35-19"><a href="#cb35-19" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb35-20"><a href="#cb35-20" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb35-21"><a href="#cb35-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-22"><a href="#cb35-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Chamar a função para criar e visualizar os boxplots</span></span>
<span id="cb35-23"><a href="#cb35-23" aria-hidden="true" tabindex="-1"></a><span class="fu">criar_boxplots_antes</span>(dados_trata_NA_nega, variaveis)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="trilha-completa_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="trilha-completa_files/figure-html/unnamed-chunk-7-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="trilha-completa_files/figure-html/unnamed-chunk-7-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="trilha-completa_files/figure-html/unnamed-chunk-7-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="trilha-completa_files/figure-html/unnamed-chunk-7-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="trilha-completa_files/figure-html/unnamed-chunk-7-6.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="descrição-dos-dados---resumo-estatístico" class="level2">
<h2 class="anchored" data-anchor-id="descrição-dos-dados---resumo-estatístico">2. Descrição dos dados - Resumo estatístico</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dados_trata_final)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       id          custo_frete        distancia_km     peso_carga_kg    
 Min.   :   5.0   Min.   :   29.71   Min.   :  56.72   Min.   :  594.9  
 1st Qu.: 259.2   1st Qu.: 5232.10   1st Qu.: 381.75   1st Qu.: 7621.7  
 Median : 508.5   Median : 7059.87   Median : 768.23   Median :15788.2  
 Mean   : 505.8   Mean   : 7072.09   Mean   : 758.89   Mean   :15419.2  
 3rd Qu.: 752.8   3rd Qu.: 9003.88   3rd Qu.:1131.55   3rd Qu.:22868.6  
 Max.   :1000.0   Max.   :14637.36   Max.   :1499.59   Max.   :29982.7  
 consumo_combustivel_kml temperatura_ambiente   hora_envio      
 Min.   : 3.017          Min.   :-9.998       Min.   : 0.02264  
 1st Qu.: 5.882          1st Qu.: 1.894       1st Qu.: 6.05883  
 Median : 8.858          Median :14.192       Median :11.76967  
 Mean   : 8.921          Mean   :14.485       Mean   :11.97404  
 3rd Qu.:12.112          3rd Qu.:26.954       3rd Qu.:17.68722  
 Max.   :14.990          Max.   :39.887       Max.   :23.98441  </code></pre>
</div>
</div>
</section>
<section id="análise-de-correlação-entre-as-variáveis" class="level2">
<h2 class="anchored" data-anchor-id="análise-de-correlação-entre-as-variáveis">3. Análise de correlação entre as variáveis</h2>
<p>Gerar a matriz de correlação para avaliar as relações entre as variáveis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Matriz de correlações</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>correlacoes <span class="ot">&lt;-</span> <span class="fu">cor</span>(dados_trata_final[, <span class="fu">c</span>(<span class="st">"custo_frete"</span>, <span class="st">"distancia_km"</span>, <span class="st">"peso_carga_kg"</span>,<span class="st">"consumo_combustivel_kml"</span>, <span class="st">"temperatura_ambiente"</span>, <span class="st">"hora_envio"</span>)])</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(correlacoes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        custo_frete distancia_km peso_carga_kg
custo_frete              1.00000000  0.806287415   0.371516853
distancia_km             0.80628742  1.000000000   0.027757999
peso_carga_kg            0.37151685  0.027757999   1.000000000
consumo_combustivel_kml  0.25314980 -0.003702946   0.001267441
temperatura_ambiente    -0.01136215 -0.012310019  -0.051386751
hora_envio               0.05128566  0.048301667   0.007556316
                        consumo_combustivel_kml temperatura_ambiente
custo_frete                         0.253149803          -0.01136215
distancia_km                       -0.003702946          -0.01231002
peso_carga_kg                       0.001267441          -0.05138675
consumo_combustivel_kml             1.000000000           0.02972543
temperatura_ambiente                0.029725431           1.00000000
hora_envio                          0.035766235          -0.06982589
                          hora_envio
custo_frete              0.051285656
distancia_km             0.048301667
peso_carga_kg            0.007556316
consumo_combustivel_kml  0.035766235
temperatura_ambiente    -0.069825891
hora_envio               1.000000000</code></pre>
</div>
</div>
<p><strong>ATIVIDADE:<br>
Usar a biblioteca ‘coorplot’ para exibir de forma gráfica a matriz de correlação<br>
</strong>Obs: use a função de correlação para os dados tratados finais: cor(dados_trata_final[, c(“var1”, “var2”, “var3” etc)])<br>
Você também pode usar o vetor que eu já criei anteriormente que guardou esses valores de correlação</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(correlacoes, <span class="at">method =</span> <span class="st">"color"</span>, <span class="at">type =</span> <span class="st">"lower"</span>, </span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">tl.col =</span> <span class="st">"black"</span>, <span class="at">tl.srt =</span> <span class="dv">45</span>, <span class="at">addCoef.col =</span> <span class="st">"black"</span>, </span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">title =</span> <span class="st">"Matriz de Correlação"</span>, <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>), </span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">cl.pos =</span> <span class="st">"b"</span>, <span class="at">col =</span> corrplot<span class="sc">::</span><span class="fu">COL2</span>(<span class="st">"RdYlBu"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="trilha-completa_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="verificar-pressupostos-da-regressão---garantir-validade-do-modelo" class="level2">
<h2 class="anchored" data-anchor-id="verificar-pressupostos-da-regressão---garantir-validade-do-modelo">4. Verificar pressupostos da regressão - garantir validade do modelo</h2>
<section id="ausência-de-multicolinearidade-vif-ou-matriz-de-correlação." class="level3">
<h3 class="anchored" data-anchor-id="ausência-de-multicolinearidade-vif-ou-matriz-de-correlação.">4.1 Ausência de multicolinearidade (VIF ou matriz de correlação).</h3>
<p>Fator de Inflação da Variância (VIF): mede o quanto a variância de um coeficiente de regressão é inflada devido à multicolinearidade</p>
<p>Abaixo de 5: multicolinearidade baixa;</p>
<p>Acima de 5: multicolinearidade relevante. Rever modelo</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>modelo_vif <span class="ot">&lt;-</span> <span class="fu">lm</span>(custo_frete <span class="sc">~</span> distancia_km <span class="sc">+</span> peso_carga_kg <span class="sc">+</span> consumo_combustivel_kml <span class="sc">+</span> temperatura_ambiente <span class="sc">+</span> hora_envio, <span class="at">data =</span> dados_trata_final)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(modelo_vif)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           distancia_km           peso_carga_kg consumo_combustivel_kml 
               1.003178                1.003403                1.002362 
   temperatura_ambiente              hora_envio 
               1.008634                1.008653 </code></pre>
</div>
</div>
</section>
<section id="linearidade" class="level3">
<h3 class="anchored" data-anchor-id="linearidade">4.2 Linearidade</h3>
<p>O relacionamento entre a variável dependente e as variáveis independentes deve ser linear. Desse modo, a mudança na variável dependente será proporcional à mudança de cada variável independente, enquanto as outras forem constantes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(modelo_vif<span class="sc">$</span>fitted.values, <span class="fu">residuals</span>(modelo_vif), </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Resíduos vs Valores Preditos"</span>, </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Valores Preditos"</span>, <span class="at">ylab =</span> <span class="st">"Resíduos"</span>)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="trilha-completa_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="independência-dos-erros" class="level3">
<h3 class="anchored" data-anchor-id="independência-dos-erros">4.3 Independência dos erros</h3>
<p>Os resíduos devem ser independentes entre si; o erro de uma observação não deve estar relacionado ao valor do erro de outra observação.</p>
<p>Verificar a interdependência com o teste Durbin-Watson. Se os resultados forem próximos de 2, podemos considerar ausência de autocorrelação serial</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">durbinWatsonTest</span>(modelo_vif)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> lag Autocorrelation D-W Statistic p-value
   1     -0.05474319      2.102387   0.108
 Alternative hypothesis: rho != 0</code></pre>
</div>
</div>
</section>
<section id="homocedasticidade" class="level3">
<h3 class="anchored" data-anchor-id="homocedasticidade">4.4 Homocedasticidade</h3>
<p>A variância dos resíduos deve ser constante em todos os níveis de valores previstos. Ou seja, a dispersão dos pontos em torno da linha de regressão deve ser similar a toda a extensão dos dados.</p>
<p>Usando o teste Breusch-Pagan: p-valor deve ser maior do que o nível de significância estabelecido (5%) (aceita H0 do teste)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bptest</span>(modelo_vif)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  modelo_vif
BP = 5.7402, df = 5, p-value = 0.3323</code></pre>
</div>
</div>
</section>
<section id="verificar-a-normalidade-dos-resíduos" class="level3">
<h3 class="anchored" data-anchor-id="verificar-a-normalidade-dos-resíduos">4.5 Verificar a normalidade dos resíduos</h3>
<p>Os erros devem seguir uma distribuição normal.</p>
<p>Teste de Shapiro-Wilk: W varia entre 0 e 1. Valor deve ser próximo de 1. p-valor deve ser maior do que o nível de significância estabelecido (5%) (aceita H0 do teste)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="fu">residuals</span>(modelo_vif))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  residuals(modelo_vif)
W = 0.99867, p-value = 0.686</code></pre>
</div>
</div>
<p>Outra forma interessante de verificar a normalidade dos resíduos é a análise do gráfico Q-Q.</p>
<p><strong>ATIVIDADE:<br>
Desenvolva o gráfico Q-Q para o vetor ‘modelo_vif’</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Gráfico Q-Q</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>residuos <span class="ot">&lt;-</span> <span class="fu">residuals</span>(modelo_vif)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(residuos), <span class="fu">aes</span>(<span class="at">sample =</span> residuos)) <span class="sc">+</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq</span>(<span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span>  <span class="co"># Pontos do gráfico Q-Q</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>(<span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span>  <span class="co"># Linha de referência</span></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Q-Q Plot dos Resíduos"</span>, </span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Quantis Teóricos"</span>, </span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Quantis dos Resíduos"</span>) <span class="sc">+</span></span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="trilha-completa_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="calcular-a-amostra---verificar-se-o-tamanho-da-amostra-é-adequado" class="level2">
<h2 class="anchored" data-anchor-id="calcular-a-amostra---verificar-se-o-tamanho-da-amostra-é-adequado">5. Calcular a amostra - verificar se o tamanho da amostra é adequado</h2>
<p>Estimar o tamanho mínimo necessário com base nos preditores e no poder estatístico.</p>
<p>N=v+u+1<br>
<em>(Tamanho mínimo da amostra é: graus de liberdade residual + nível de significância + 1)</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>amostra <span class="ot">&lt;-</span> <span class="fu">pwr.f2.test</span>(<span class="at">u =</span> <span class="dv">5</span>, <span class="at">v =</span> <span class="cn">NULL</span>, <span class="at">f2 =</span> <span class="fl">0.15</span>, <span class="at">sig.level =</span> <span class="fl">0.05</span>, <span class="at">power =</span> <span class="fl">0.8</span>)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(amostra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Multiple regression power calculation 

              u = 5
              v = 85.21369
             f2 = 0.15
      sig.level = 0.05
          power = 0.8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="fl">85.21</span><span class="sc">+</span><span class="dv">5</span><span class="sc">+</span><span class="dv">1</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(N)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 91.21</code></pre>
</div>
</div>
</section>
<section id="hipóteses" class="level2">
<h2 class="anchored" data-anchor-id="hipóteses">6. Hipóteses</h2>
<p>O teste de hipótese é importante para o modelo porque, com ele, testamos a significância dos coeficientes de regressão. Avalia se a relação entre as variáveis dependente e independentes tem relação ou se ocorrem por acaso.</p>
<ul>
<li><p><strong>Hipótese Nula (H0)</strong>: Não há relação significativa entre as variáveis independentes (distância, peso da carga, etc.) e o custo do frete.</p></li>
<li><p><strong>Hipótese Alternativa (H1</strong>): Ao menos uma variável tem relação significativa com o custo do frete.</p></li>
</ul>
</section>
<section id="modelar-e-analisar-a-regressão" class="level2">
<h2 class="anchored" data-anchor-id="modelar-e-analisar-a-regressão">7. Modelar e analisar a regressão</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar o modelo de regressão</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(custo_frete <span class="sc">~</span> distancia_km <span class="sc">+</span> peso_carga_kg <span class="sc">+</span> consumo_combustivel_kml <span class="sc">+</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>               temperatura_ambiente <span class="sc">+</span> hora_envio, <span class="at">data =</span> dados_trata_final)</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Resumo do modelo</span></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = custo_frete ~ distancia_km + peso_carga_kg + consumo_combustivel_kml + 
    temperatura_ambiente + hora_envio, data = dados_trata_final)

Residuals:
    Min      1Q  Median      3Q     Max 
-3555.7  -727.2   -10.6   715.7  3252.0 

Coefficients:
                          Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)             -46.670960 141.930627  -0.329    0.742    
distancia_km              4.917884   0.079846  61.592   &lt;2e-16 ***
peso_carga_kg             0.106283   0.003938  26.987   &lt;2e-16 ***
consumo_combustivel_kml 192.452474   9.756069  19.726   &lt;2e-16 ***
temperatura_ambiente      1.625960   2.361985   0.688    0.491    
hora_envio                0.612211   4.928995   0.124    0.901    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1059 on 972 degrees of freedom
Multiple R-squared:  0.8375,    Adjusted R-squared:  0.8367 
F-statistic:  1002 on 5 and 972 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ANOVA do modelo</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: custo_frete
                         Df     Sum Sq    Mean Sq   F value Pr(&gt;F)    
distancia_km              1 4363513418 4363513418 3889.3321 &lt;2e-16 ***
peso_carga_kg             1  818804823  818804823  729.8256 &lt;2e-16 ***
consumo_combustivel_kml   1  438710071  438710071  391.0356 &lt;2e-16 ***
temperatura_ambiente      1     520831     520831    0.4642 0.4958    
hora_envio                1      17308      17308    0.0154 0.9012    
Residuals               972 1090504722    1121918                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>ATIVIDADE<br>
Escreva a equação da regressão</strong></p>
<p>Custo&nbsp;Frete=−46.67 + 4.92*distancia_km + 0.11*peso_carga_kg + 192.45*consumo_combustivel_kml + 1.63*temperatura_ambiente + 0.61*hora_envio</p>
</section>
<section id="interpretar-e-relatar-o-resultado" class="level2">
<h2 class="anchored" data-anchor-id="interpretar-e-relatar-o-resultado">8. Interpretar e relatar o resultado</h2>
<p><strong>temperatura_ambiente</strong> e <strong>hora_envio</strong> não são estatisticamente significativos, pois p&gt;0.05; ou seja, tem impacto irrelevante no modelo.</p>
<p>Resíduos: Mediana próxima de zero. Erros não possuem um viés sistemático significativo. O erro padrão dos resíduos mostrou que, em média, houve uma diferença de R$1.059,00 entre o valor predito e o valor real no custo do frete.</p>
<p>A estatística F (razão entre a variabilidade explicada pelo modelo e a variabilidade residual) apresentou um valor alto, 1002, o que demonstra que o modelo tem boa predição da variabilidade dos resultados. O p-valor da estatística F próximo de 0 mostra que ao menos uma das variáveis independentes tem impacto significativo no custo do frete.</p>
<p>R2 0.8375 e R2 ajustado de 0.8367, demonstrando que o modelo é consistente e tem um alto valor explicativo, apesar da pequena penalização pela inclusão de variáveis irrelevantes.</p>
<p>A análise da variância do modelo reforça a ideia de que as variáveis Distância, Peso da carga e Consumo de combustível contribuem bastante para o modelo e que as variáveis Temperatura do ambiente e Hora do envio não são significativas.</p>
<p><strong>ATIVIDADE<br>
Ajustar o modelo para que tenha apenas as variáveis relevantes e comparar o resultado</strong></p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>